core/security/src/main/java/com/backtothefuture/security/config/SpringSecurityConfig.java
- http://localhost:8000, http://127.0.0.1:8000 오리진 추가
- OPTION 메서드 프리플라이트 요청에 대해서 허용 처리
resolve: #12
=> fix: swagger 에서 api 통신할때 cors 발생하던 부분 처리

api/member/build.gradle, api/member/src/main/java/com/backtothefuture/member/controller/MemberController.java, api/member/src/main/java/com/backtothefuture/member/dto/response/LoginTokenDto.java, api/member/src/main/java/com/backtothefuture/member/service/MemberService.java, api/member/src/main/resources/application.yml, api/member/src/test/java/com/backtothefuture/member/controller/MemberControllerTest.java, core/domain/build.gradle, core/domain/src/main/java/com/backtothefuture/domain/DomainConfig.java, core/domain/src/main/java/com/backtothefuture/domain/common/repository/RedisRepository.java, core/domain/src/main/resources/application-domain.yml, core/infra/src/main/java/com/backtothefuture/infra/config/QuerydslConfig.java, core/infra/src/main/java/com/backtothefuture/infra/config/RedisConfig.java
- 로그인 시 반환할때 refresh token값도 반환하도록 추가했습니다.
- loginTokenDto class -> record로 수정했습니다.
- 앱 애플리케이션이므로 http-only 쿠키 설정을 하지 않았습니다.
- redis에 memberId를 키값으로 refreshToken값을 저장합니다.
resolve: #16
=> feat: refresh token 발급 추가 및 logintokenDto class에서 record로 변경 #16

api/member/src/main/java/com/backtothefuture/member/annotation/EnumTypeMisMatch.java, api/member/src/main/java/com/backtothefuture/member/annotation/ProviderTypeValidator.java, api/member/src/main/java/com/backtothefuture/member/annotation/RolesTypeValidator.java, api/member/src/main/java/com/backtothefuture/member/controller/MemberController.java, api/member/src/main/java/com/backtothefuture/member/dto/request/OAuthLoginDto.java, api/member/src/main/java/com/backtothefuture/member/dto/response/KakaoUserInfo.java, api/member/src/main/java/com/backtothefuture/member/dto/response/NaverUserInfo.java, api/member/src/main/java/com/backtothefuture/member/exception/GlobalExceptionHandler.java, api/member/src/main/java/com/backtothefuture/member/service/KakaoOAuthService.java, api/member/src/main/java/com/backtothefuture/member/service/MemberService.java, api/member/src/main/java/com/backtothefuture/member/service/NaverOAuthService.java, api/member/src/main/java/com/backtothefuture/member/service/OAuthService.java, api/member/src/test/java/com/backtothefuture/member/controller/MemberControllerTest.java, core/domain/src/main/java/com/backtothefuture/domain/member/enums/ProviderType.java, core/domain/src/main/java/com/backtothefuture/domain/member/enums/RolesType.java, core/domain/src/main/java/com/backtothefuture/domain/member/repository/MemberRepository.java
- custom annotation을 사용하여 field validation를 했습니다. 비즈니스 코드와 검증 코드를 분리하여 관심사를 분리하였습니다.
- class type으로 존재하는 dto를 record type으로 수정했습니다.
-  record type은 값이 불변하는 객체인데 memberLoginDto, memberRegisterDto의 경우 service layer에서 set 메소드를 호출함으로 class type으로 유지했습니다. 
- oauth 소셜 로그인 테스트 코드와 api 명세서를 작성했습니다.
- **테스트 코드 작성이 익숙치 않아 많이 미흡합니다,, 많은 피드백,, 부탁드립니다 ㅎㅎ** 
- **궁금한 점**
-  하나의 custom annotation을 사용할 때,
provierType이 null인 경우와 KAKAO2처럼 일치하는 값이 없는 경우인 2가지 경우가 존재할 때 각각의 경우 서로 다른 
message를 출력하는 방법이 있을까요? 
KAKAO2처럼 존재하지 않는 값이 오면 json parse 과정에서 null을 반환하여 아예 오지 않았을 때와 같은 
annotation(@Valid)로 검증이 수행됩니다. @EnumTypeMisMatch으로 두 가지의 경우 다른 메시지를 출력하도록 구현하고 싶은데 좋은 방법이 있으면 알려주세요!
- custom annotation reference
- https://www.baeldung.com/spring-mvc-custom-validator
- spring rest docs reference
- …
=> PR(#22) 리뷰 반영

core/infra/src/main/resources/application-infra.yml
```
data.redis.port: ${SPRING_REDIS_HOST:6379} -> ${SPRING_REDIS_PORT:6379}
```
해당 오타 수정했습니다.
resolve: #40
=> fix: 오기입한 redis 설정 변수명 수정 #40

.github/workflows/integration-test.yml, api/member/build.gradle, api/member/src/test/java/com/backtothefuture/member/config/BfTestConfig.java, api/member/src/test/java/com/backtothefuture/member/controller/MemberControllerTest.java, core/infra/src/main/java/com/backtothefuture/infra/config/RedisConfig.java
- testcontainer 적용해 db, redis를 띄운 상태로 통합테스트 수행하도록 설정
- testcontainer 의존성 추가
- property 가져오는 부분 오타 수정
- github action으로 pr시 테스트 수행하도록 설정
- 혹시 infra > src > test > java > com > backtothefuture 이런식으로 infra의 test경로에 test container 관련 test를 위치했을때, api쪽에서 import가 가능한 방법이 있을까요?
- 테스트 관련 설정이라, src 하위에 넣는 것도 아닌 것 같아서, api 마다 추가해줘야 하는 구조로 짰는데, 혹시 더 나은 방법을 아신다면 공유 부탁드릴게요 🥲
resolve: #49
=> test: testcontainer 설정, pr시 테스트 설정

api/member/src/main/java/com/backtothefuture/member/controller/MemberController.java, api/member/src/main/java/com/backtothefuture/member/service/KakaoOAuthService.java, api/member/src/main/java/com/backtothefuture/member/service/NaverOAuthService.java, api/member/src/main/java/lombok.config, api/member/src/test/java/com/backtothefuture/member/controller/MemberControllerTest.java, lombok.config
- Lombok을 사용할 때, ` @RequiredArgsConstructor ` 와 `@Qualifier` 를 함께 사용하면 `@Qualifier`를 인지 못하는 오류가 존재하여 lombok.config파일을 생성하고 
`lombok.copyableAnnotations += org.springframework.beans.factory.annotation.Qualifier` 를 추가하였습니다.
- 작업 내용으로 인해, #60 문제는 해결하였지만 api/member 모듈을 빌드 할 시 
MemberControllerTest > 일반 로그인 테스트 FAILED                                                                               
java.lang.IllegalStateException at DefaultCacheAwareContextLoaderDelegate.java:180                                         
Caused by: org.springframework.beans.factory.UnsatisfiedDependencyException at ConstructorResolver.java:798            
Caused by: org.springframework.beans.factory.BeanCreationException at AutowiredAnnotationBeanPostProcessor.java:514
Caused by: java.lang.IllegalArgumentException …
=> fix: @Qualifier를 인식하지 못하는 오류 해결

api/store/src/main/java/com/backtothefuture/store/controller/ProductController.java, api/store/src/main/java/com/backtothefuture/store/dto/request/ProductUpdateDto.java, api/store/src/main/java/com/backtothefuture/store/dto/response/ProductResponseDto.java, api/store/src/main/java/com/backtothefuture/store/service/ProductService.java, api/store/src/test/java/com/backtothefuture/store/controller/ProductControllerTest.java, core/domain/src/main/java/com/backtothefuture/domain/product/Product.java, core/domain/src/main/java/com/backtothefuture/domain/product/repository/ProductRepository.java, core/security/src/main/java/com/backtothefuture/security/config/SpringSecurityConfig.java, docs/openapi/store-openapi.yaml
- 상품 단건 조회 api 추가
- 상품 전체 조회 api (정렬, 검색키워드, 페이지네이션 등 추가 및 개선이 필요함) 추가
- 상품 업데이트 api 추가
- 가게에 대한 상품 전체정보는 /store/{storeId}에서 상품 정보 & 가게 정보를 같이 가져오는 편이 낫다고 생각해서 제외함
- 보통 전체 가게 목록에서 클릭 -> 가게 정보와 상품 정보를 같이 조회하기 때문
- 기타 테스트 및 문서화 코드 추가
- **security 관련**: 조회는 슬랙에서 비회원 유저도 가능하도록 하자는 이야기가 있어 전체허용으로 설정했습니다. 
resolves: #27
=> feat: 상품 관련 api 추가, 테스트-문서화 추가

.github/workflows/integration-test.yml, api/store/build.gradle, api/store/src/test/java/com/backtothefuture/store/controller/ProductControllerTest.java, core/infra/src/main/resources/application-infra.yml, docker-compose.yml
- product 테스트에 통합테스트 설정 추가
- docker compose의 db url을 mysql 설정으로 변경
- db 컨테이너가 다 뜨지 않은 상태에서 연결을 시도하고 실패하는 문제가 있어 `healthcheck` 설정 추가
- Spring <-> Mysql 연결시 Dialect 관련 에러가 발생해 Dialect 수정
- Hibernate6 이상부터는 버전명을 명시하지 않아도 된다고 합니다.
- 참고: https://docs.jboss.org/hibernate/orm/6.0/migration-guide/migration-guide.html#_dialects 
+) 추가
테스트 성공했습니다. 추가로 한 작업은
- Github Action에서 루트 디렉토리에 .env 파일 생성
- Github Secret에 member api application.yml 정보 셋팅
resolves: #63, #71
=> product 테스트에 통합테스트 추가, 빌드 설정 수정

api/store/src/main/java/com/backtothefuture/store/controller/ProductController.java, api/store/src/main/java/com/backtothefuture/store/controller/StoreController.java, api/store/src/main/java/com/backtothefuture/store/dto/request/StoreRegisterDto.java, api/store/src/test/java/com/backtothefuture/store/controller/ProductControllerTest.java, api/store/src/test/java/com/backtothefuture/store/controller/StoreControllerTest.java, docs/openapi/store-openapi.yaml
- store api 문서화 추가
- url을 `/store` -> `/stores`로 변경
resolves: #36
=> docs: /stores 문서화 추가, api url store -> stores로 변경 #36

api/event/build.gradle, build.gradle, core/domain/src/main/java/com/backtothefuture/domain/member/Member.java, core/domain/src/main/java/com/backtothefuture/domain/product/Product.java, core/domain/src/main/java/com/backtothefuture/domain/store/Store.java, core/infra/src/main/resources/application-infra.yml, core/infra/src/main/resources/schema.sql, docs/openapi/event-openapi.yaml, initdb.d/init.sql
- ddl-auto : create-drop에서 validate로 수정했습니다.
- 이에 따라 init.sql 작성했습니다.
- api 문서화 수정했습니다.
- https://mycup.tistory.com/382
- https://ttl-blog.tistory.com/117
-   @LOB 사용 시, MySQL에서 문자열은 TEXT 데이터 타입을 사용해야 함.
resolves: #82
=> Fix: ddl-atuo : create-drop 시 발생하는 테이블 생성 에러 수정

api/event/src/main/resources/application.yml
- @Value를 사용한 환경 변수 주입 안 되는 에러로 인해 임시 문자열 처리했습니다.
resolves: #84
=> fix: 환경 변수 주입 안 되는 에러로 인해 임시 문자열 처리

.github/workflows/integration-test.yml, api/event/build.gradle, api/event/src/main/java/com/backtothefuture/event/EventApplication.java, api/event/src/main/java/com/backtothefuture/event/controller/CertificateController.java, api/event/src/main/java/com/backtothefuture/event/dto/request/MailCertificateRequestDto.java, api/event/src/main/java/com/backtothefuture/event/exception/CertificateException.java, api/event/src/main/java/com/backtothefuture/event/exception/GlobalExceptionHandler.java, api/event/src/main/java/com/backtothefuture/event/exception/VerifyMailFailException.java, api/event/src/main/java/com/backtothefuture/event/service/CertificateService.java, api/event/src/main/java/com/backtothefuture/event/service/CoolsmsService.java, api/event/src/main/java/com/backtothefuture/event/service/MailService.java, api/event/src/main/resources/application.yml, api/event/src/main/resources/templates/mail/verify-fail.html, api/event/src/main/resources/templates/mail/verify-success.html, api/event/src/test/java/com/backtothefuture/event/EventApplicationTests.java, core/domain/src/main/java/com/backtothefuture/domain/common/enums/CertificateErrorCode.java, core/domain/src/main/java/com/backtothefuture/domain/common/repository/RedisRepository.java, core/domain/src/main/resources/application-domain.yml, core/infra/src/main/resources/application-infra.yml, core/infra/src/testFixtures/java/com/backtothefuture/infra/config/BfTestConfig.java, core/security/src/main/java/com/backtothefuture/security/config/SpringSecurityConfig.java, docker-compose.yml, docs/openapi/event-openapi.yaml
- 인증 메일 전송 api 추가
- 인증 메일 검증 api 추가
- 이 api는 프론트에서 활용하는 api가 아니라, 메일 수신자가 클릭하는 링크 입니다.
- 인증 메일 검증 상태 확인 api 추가
- 인증 완료 시 true, 미완료시 false
- #86 관련 버그 수정 :: 자세한건 해당 이슈에 적어놓았습니다. 
- 
- 메일 전송 결과
- 성공 시
- 실패 시
- API 문서
resolves: #46, #86
=> feat: 인증 메일 api 추가 및 문서화, 로컬환경 설정 버그 수정

api/store/src/main/java/com/backtothefuture/store/dto/request/ReservationRequestDto.java, api/store/src/main/java/com/backtothefuture/store/dto/request/StoreRegisterDto.java, api/store/src/main/java/com/backtothefuture/store/service/ReservationService.java, api/store/src/main/resources/application.yml, api/store/src/test/java/com/backtothefuture/store/controller/ReservationConcurrencyTest.java, api/store/src/test/java/com/backtothefuture/store/controller/ReservationControllerTest.java, api/store/src/test/java/com/backtothefuture/store/controller/StoreControllerTest.java, core/domain/src/main/java/com/backtothefuture/domain/common/enums/ReservationErrorCode.java, core/domain/src/main/java/com/backtothefuture/domain/reservation/Reservation.java, core/domain/src/main/java/com/backtothefuture/domain/store/Store.java, core/infra/src/main/resources/application-testContainers.yml, core/infra/src/testFixtures/java/com/backtothefuture/infra/config/BfTestConfig.java, core/infra/src/testFixtures/resources/init.sql, docs/openapi/store-openapi.yaml, initdb.d/init.sql
- 영업 시작/종료 시간, 예약 시간 기능 추가했습니다.
- 이에 따라 테스트 코드, 문서화를 수정했습니다.
- intellij-java-wooteco-style.xml 를 따랐습니다.
- test용 profile를 분리하고 test containers DB 초기화를 하였습니다.
- ReservationConcurrencyTest의 경우 mockito를 사용하지 않고 실제 insert 쿼리 문을 사용하는 테스트입니다. 이로 인해 schema.sql와 같이 테스트 DB를 초기화해주는 DDL 스크립트가 필요했습니다. 하지만 sql.init.mode : always를 사용하여 테스트 DB를 초기화하는 schema.sql의 경우에 init.sql와 충돌이 발생하였습니다. 
- 첫 번째 시도: workflow에 mysql와 schema.sql을 만들고 해당 mysql에 DDL을 실행한 후에 gradle build를 하고자 했습니다.
- 하지만 이러면 build 결과물에 schema.sql 가 포함되어 결과적으로 동일한 에러를 발생시켰습니다.
- 두 번째 시도: 현재 test containers를 사용하고 있었는데 이를 활용하여 test containers 속 DB에 DDL 스크립트를 적용시키고 ReservationConcurrencyTest 속 쿼리 문을 test containers DB에 날렸습니다.
**부족한 점**
- test containers의 개념이 부족하여 test 코드를 작성할 때 이를 적극적으로 활용하지 못했습니다. 이로 인해 test container DB 초기화 하는 생각을 늦게 했습니다.
- …
=> feat: 영업 시작/종료 시간, 예약 시간 기능 추가

api/event/src/main/java/com/backtothefuture/event/controller/CertificateController.java, api/event/src/main/java/com/backtothefuture/event/dto/request/MailCertificateRequestDto.java, api/event/src/main/java/com/backtothefuture/event/dto/response/CertificateMailResponseDto.java, api/event/src/main/java/com/backtothefuture/event/service/CertificateService.java, api/event/src/main/resources/application.yml, api/event/src/test/java/com/backtothefuture/event/EventApplicationTests.java, core/domain/build.gradle, core/domain/src/main/java/com/backtothefuture/domain/common/repository/RedisRepository.java, core/domain/src/main/java/com/backtothefuture/domain/response/BfResponse.java, core/domain/src/main/resources/application-domain.yml, docs/openapi/event-openapi.yaml
- 이메일 인증메일 전송 -> 메일 본문의 링크 클릭 -> 인증 방식에서
- 이메일 인증메일 전송 -> 메일 본문의 인증코드 프론트 화면에 입력 -> 검증 방식으로 변경
- swagger 문서화
**1. `ResponseEntity<BfResponse<CertificateMailResponseDto>>` 처럼 dto 정의할 경우**
```
useReturnTypeSchema = true
```
옵션으로 문서화 가능합니다.
**2. `Map.of(..)`로 응답할 경우**
이때 문서화 방법은 찾지 못했습니다.
다만 이렇게 응답하는 경우 data 에 대한 필드가 하나인 경우가 대부분이라,
example을 정의하는것으로 대체해도 괜찮을 것 같다는 생각이 듭니다.
resolves: #117
=> feat: 이메일 인증방식 변경 #117

api/store/src/main/java/com/backtothefuture/store/controller/ProductController.java, api/store/src/main/java/com/backtothefuture/store/controller/StoreController.java, api/store/src/main/java/com/backtothefuture/store/dto/request/ProductRegisterDto.java, api/store/src/main/java/com/backtothefuture/store/dto/request/StoreRegisterDto.java, api/store/src/main/java/com/backtothefuture/store/dto/response/ProductGetListResponseDto.java, api/store/src/main/java/com/backtothefuture/store/dto/response/ProductGetOneResponseDto.java, api/store/src/main/java/com/backtothefuture/store/service/ProductService.java, api/store/src/main/java/com/backtothefuture/store/service/StoreService.java, api/store/src/test/java/com/backtothefuture/store/controller/ProductControllerTest.java, core/infra/src/main/java/com/backtothefuture/infra/config/MultipartJackson2HttpMessageConverter.java, docs/openapi/store-openapi.yaml
- `@RequestParts` 사용시 각각의 content type을 지정해줘야 하는데, swagger에서 문서화 - 테스트 했을때 아래 에러가 나타남
```
HttpMediaTypeNotSupportedException: Content type 'application/octet-stream' not supported
``` 
- swagger에서 각 필드별로 content-type이 지정되지 않아 발생하는 문제.
```java
// AbstractMessageConverterMethodArgumentResolver.java
if (contentType == null) {
noContentType = true;
contentType = MediaType.APPLICATION_OCTET_STREAM;
} // content-type이 null일경우 application/octet-stream으로 설정한다.
```
- application/octet-stream을 처리해주는 컨버터 추가
- store, product 등록 API 문서화 추가
- product 수정, 조회, 삭제 API 문서화 추가
resolves: #134
=> store, product API 문서화, octet-stream 컨버터 추가

api/store/src/test/java/com/backtothefuture/global/RestAssuredTest.java, api/store/src/test/resources/reset.sql, build.gradle, core/infra/src/main/resources/application-infra.yml
- RestAssured 환경설정했습니다.
- RestAssured 설정 후 임시로 테스트 코드를 돌려보니, s3 관련 설정 값이 바인딩이 안되는 이슈가 있었습니다.
- 유선님이 말씀주신 것처럼 yml 파일에 카멜케이스를 수정하니 이슈가 해결되었습니다.
- 테스트 모듈에 있는 클래스 파일은 모듈 간 참조가 안되어 store외에 모듈에서 RestAssured 테스트를 진행하고 싶으면 `RestAssuredTest.java`와 똑같이 파일을 생성해서 사용하면 됩니다.
- 사용 방법은 아래와 같이 이전에 테스트 실행 시 `BfTestConfig` 상속 받았던 것처럼 RestAssured를 상속받으면 됩니다.
- 각 테스트 메서드 간 멱등성을 보장하기 위해 테스트 메서드 실행 후 모든 테이블을 truncate하는 SQL을 실행하도록 설정했습니다.
#115
=> RestAssured 환경 설정

api/store/src/main/java/com/backtothefuture/store/controller/ReviewController.java, api/store/src/main/java/com/backtothefuture/store/dto/request/ReviewCreateRequest.java, api/store/src/main/java/com/backtothefuture/store/dto/request/ReviewUpdateRequest.java, api/store/src/main/java/com/backtothefuture/store/dto/response/ReviewsReadResponse.java, api/store/src/main/java/com/backtothefuture/store/exception/ReviewException.java, api/store/src/main/java/com/backtothefuture/store/service/ReviewService.java, core/domain/src/main/java/com/backtothefuture/domain/common/BaseEntity.java, core/domain/src/main/java/com/backtothefuture/domain/common/enums/ReviewErrorCode.java, core/domain/src/main/java/com/backtothefuture/domain/common/util/s3/S3Util.java, core/domain/src/main/java/com/backtothefuture/domain/review/Review.java, core/domain/src/main/java/com/backtothefuture/domain/review/repository/ReviewRepository.java, core/domain/src/main/java/com/backtothefuture/domain/store/Store.java, core/infra/src/testFixtures/resources/init.sql, core/security/src/main/java/com/backtothefuture/security/config/SpringSecurityConfig.java, initdb.d/init.sql
- 리뷰 CRUD API 구현
- 리뷰 작성/수정 시 구매일자 기준 3일 이내에만 가능합니다.
-  현재까지 구현된 로직 기준 픽업 완료 일시를 확인할 수 없어서 TODO 로 주석 남겨 놓았습니다.
- 유선님이 이슈에 댓글 남겨주신 부분 확인했습니다.
- 사장님 댓글 작성 기능도 현재 미구현으로 우선 "사장님 댓글이 있을 시 삭제 불가"도 추후 구현할 예정입니다.
- 상점 조회 시 리뷰를 활용해야 하는 부분이 있어서 해당 PR 머지되면 상점 조회 API 마무리 하겠습니다. 
resolves: #146
=> 리뷰 CRUD API 구현

api/store/src/main/java/com/backtothefuture/store/controller/StoreController.java, api/store/src/main/java/com/backtothefuture/store/domain/SortingOption.java, api/store/src/main/java/com/backtothefuture/store/dto/response/StoreResponse.java, api/store/src/main/java/com/backtothefuture/store/service/StoreService.java, core/domain/src/main/java/com/backtothefuture/domain/common/enums/StoreErrorCode.java, core/domain/src/main/java/com/backtothefuture/domain/store/Store.java, core/domain/src/main/java/com/backtothefuture/domain/store/repository/StoreRepository.java, core/infra/src/testFixtures/resources/init.sql, initdb.d/init.sql
- 정렬 옵션없는 가게 목록 조회 API 구현했습니다.
- 별점/거리순 정렬 완료하고 가게 평점 업데이트하는 로직이 완성하겠습니다!
resolves: #148
=> 정렬 옵션없는 가게 목록 조회 API 구현

api/member/src/main/java/com/backtothefuture/member/controller/MemberController.java, api/member/src/main/java/com/backtothefuture/member/dto/request/MemberPasswordResetRequestDto.java, api/member/src/main/java/com/backtothefuture/member/service/MemberService.java, core/domain/src/main/java/com/backtothefuture/domain/common/enums/MemberErrorCode.java, core/domain/src/main/java/com/backtothefuture/domain/member/Member.java, core/security/src/main/java/com/backtothefuture/security/config/SpringSecurityConfig.java
162번과 겹치는 내용이 있어, 162번에서 브랜치를 땄습니다.
164 -> rebase merge -> 162 -> squash merge -> dev 하려고 합니다.
- 비밀번호 재설정 API 추가
- 프론트에서 이메일 인증 완료후 요청했다는 것을 전제
- 비밀번호 재설정시 비밀번호 확인란도 함께 검증 (프론트와 이중 검증)
- 관리자이거나, 본인인경우 비밀번호 재설정 가능 
- 응답은 204(no content)
resolves: #164
=> feat: 비밀번호 재설정 API 추가 #164

api/store/src/main/java/com/backtothefuture/store/dto/response/MemberDoneReservationListDto.java, api/store/src/main/java/com/backtothefuture/store/dto/response/MemberProgressReservationResponseDto.java, api/store/src/main/java/com/backtothefuture/store/dto/response/ProgressReservationHistoryResponseDto.java, api/store/src/main/java/com/backtothefuture/store/dto/response/ReservationProductNameResponseDto.java, api/store/src/main/java/com/backtothefuture/store/service/ReservationHistoryService.java
- 진행 중인 주문 내역, 주문 완료 내역 API 문서화를 수정했습니다.
- 기존에 실제 반환 값과 다른 json key가 스웨거 example value에 표시되었는데 이를 아래와 같이 수정했습니다.
- 진행 중인 주문 내역
- 주문 완료 내역
- **기타 공유사항에 대해 작성해 주세요.**
resolves: #178
=> docs: 주문 내역 스웨거 문서 수정
